import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Slider from "../components/slider";
import Skills from "@/components/skils";
import About from "@/components/about";
import Projects from "@/components/projects";
import SocialMedia from "@/components/socialMedia";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Slider></Slider>
      <main className={styles.main}>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/fullname.png"
            alt="hugo logo"
            width={668}
            height={337}
            priority={true}
          />
        </div>
        <Skills></Skills>
        <div className={"container"}>
          <About></About>
        </div>
        <br></br>
        <br></br>
        <div>
          <Projects></Projects>
        </div>
        <div>
          <SocialMedia />
        </div>
      </main>
    </>
  );
}
